### ISSUE TITLE
Classification of implicit instruction accesses as explicit accesses should be normative

### ISSUE THREAD

**Issue by dkruckemyer-ventana** [riscv-non-isa/riscv-ras-eri#42]
The RERI spec has an informational comment that states:

> Instruction memory accesses by a
> hart are termed as implicit accesses by the Privileged specification. However for
> the purposes of error reporting only the implicit accesses to data structures like
> the (guest) page tables used to determine the address of the instruction to fetch are
> termed as implicit accesses. The read to fetch the instruction bytes themselves are
> termed as explicit reads.

Since this is reclassifying a memory access due to an instruction fetch as something different from the base spec (*explicit* rather than implicit), it feels like this should be made normative text rather than informational.

**Comment by ved-rivos** [comment]
Will move that block of text outside the note block.

**Comment by dkruckemyer-ventana** [comment]
Minor nit (?) as well: implicit and explicit accesses are defined in the *base* spec, not the priv spec.

**Comment by ved-rivos** [comment]
Updated the reference.
