### ISSUE TITLE
Clarify what "else" represents in the control_i register

### ISSUE THREAD

**Issue by dkruckemyer-ventana** [riscv-non-isa/riscv-ras-eri#44]
The meaning of the "else" acronym is not stated anywhere. What does "else" stand for?

**Comment by gfavor** [comment]
One suggestion is to change the "*the else field is*" text to say
"*the else field
(error logging and signaling enable) is*".

Greg

**Comment by ved-rivos** [comment]
expanded the acronym  - "is enabled if error-logging-and-signaling-enable (`else`) field is set to 1."
