### ISSUE TITLE
16-bit imp_id field seems too small

### ISSUE THREAD

**Issue by MarkHillCodasip** [riscv-non-isa/riscv-ras-eri#46]
The allocation of just 16-bits to vendor_n_imp_id.imp_id to cover all of a companies portfolio of IPs and versions seems quite small to me, especially if a vendor wants to break this  broken down into subfields for classes of IP and major/minor/patch versions etc. Specifically in the case of RISCV processor implementations it seems reasonable to support a one-one mapping between RERI registers and mvendorid, marchid and mimpid.

**Comment by ved-rivos** [comment]
Its reasonable to widen the `imp_id` to 32-bits by expanding into the 16 reserved bits adjacent to it. I will post a PR shortly with a change.

**Comment by MarkHillCodasip** [comment]
Thanks!

**Comment by ved-rivos** [comment]
Update in PR #47
