### ISSUE TITLE
Question about error record overwritting rules

### ISSUE THREAD

**Issue by Groupsun** [riscv-non-isa/riscv-ras-eri#53]
In the current reri spec chapter 2.5, listing 1 describes the overwriting rules of the error record. However, it doesn't mention the following situation:

- If the `new_error` has the same severity and priority as the current logged error record.

What actions should hardware take in this situation?

BTW, is there any hardware modeling for reri spec?

**Comment by ved-rivos** [comment]
If the two errors have same severity then `MO` is set to 1 (line 3). However, if they have the same priority then condition at line 6 evaluates to false and there is no overwrite. The net of this is that a second error of the same priority and severity sets the multiple-occurred (`MO`) bit but the first error is retained.
```

1.          if ( severity(new_status) == severity(status_i) )
2.              // Second errors of the same severity set MO
3.              status_i.mo = 1
4.              // Second error of same severity overwrites previous error if it
5.              // has higher priority (status_i.pri).
6.              if ( new_status.pri > status_i.pri )
7.                  overwrite = TRUE;
8.              endif
9.          endif

```
> BTW, is there any hardware modeling for reri spec?

I am not aware of an open source implementation.

**Comment by Groupsun** [comment]
Thanks!
