### ISSUE TITLE
is it better to remain timestamp_i to the earliest fault/error report timestamp?

### ISSUE THREAD

**Issue by lixiaogangkkk** [riscv-non-isa/riscv-ras-eri#55]
The overwrite rules allows to update timestamp_i if a higher priority fault/error is reported. it means the RAS system can not know the first fault/error time if multiple faults/errors comes together, how could system to recover/find the trusted point? I believe it's better to keep the timestamp_i of the first fault/error, so system can notice whether there will be data/status takes system into risk.

**Comment by gfavor** [comment]
On the one hand we cannot change a ratified spec.  But one way to support what you desire within the current spec is to use the Supplemental Information Register.  Since the contents of this register are completely implementation-defined, you can use it to hold a "first error timestamp".

**Comment by ved-rivos** [comment]
Only a higher severity error overwrites a lower severity error - for instance a uncorrected error overwriting a deferred error or corrected errors. Overwriting of a corrected error by a deferred error or a deferred error by a uncorrected error is not a loss of actionable information. The corrected/deferred errors are informational but the error has either been corrected or the corruption has not yet affected computation. Uncorrected critical errors need urgent handling as they are the ones that might have affected computation. 

The other use of a timestamps is to help with correlation of errors across error records. For the correlation use case, it may be more beneficial to retain the time of the most recent error to do the correlation/causal analysis across records. 

Besides what Greg suggested, depending on the width of your timestamp, you may also hold multiple timestamps in the timestamp register itself. For instance, if the timestamp is 32-bit wide then one could hold a list of 2 timestamps in the timestamp register.

**Comment by lixiaogangkkk** [comment]
> Only a higher severity error overwrites a lower severity error - for instance a uncorrected error overwriting a deferred error or corrected errors. Overwriting of a corrected error by a deferred error or a deferred error by a uncorrected error is not a loss of actionable information. The corrected/deferred errors are informational as the error has either been corrected or the corruption has not yet affected computation. Uncorrected critical errors need urgent handling as they are the ones that might have affected computation.
> 
> The other use of a timestamps is to help with correlation of errors across error records. For the correlation use case, it may be more beneficial to retain the time of the most recent error to do the correlation/causal analysis across records.
> 
> Besides what Greg suggested, depending on the width of your timestamp, you may also hold multiple timestamps in the timestamp register itself. For instance, if the timestamp is 32-bit wide then one could hold a list of 2 timestamps in the timestamp register.

Thanks for comments, as definition higher severity or priority error can overwrites report and timestamps, it means the software guy should be very clear about these faults/errors and define the priority correctly in system.

**Comment by lixiaogangkkk** [comment]
> On the one hand we cannot change a ratified spec. But one way to support what you desire within the current spec is to use the Supplemental Information Register. Since the contents of this register are completely implementation-defined, you can use it to hold a "first error timestamp".

It's a solution. thanks a lot.
