### ISSUE TITLE
When UEC or UED Logged In Record, CE can be triggered?

### ISSUE THREAD

**Issue by yanligen** [riscv-non-isa/riscv-ras-eri#57]
![image](https://github.com/user-attachments/assets/6578144b-962b-4527-a267-932ad7f8e1fd)
![image](https://github.com/user-attachments/assets/73c39abd-155c-42fe-b55c-120e3ef32d85)
I have a question: when ue has logged in status register, if ce occurs, it will set status.ce bit and trigger ce interrupt, but if enable control.cece, why can not affect ce counter and status.ceco bit? 
another question: in overwrite rule, why status.ceco can not be overwrite?, it must be modified by software?

**Comment by ved-rivos** [comment]
> I have a question: when ue has logged in status register, if ce occurs, it will set status.ce bit and trigger ce interrupt, but if enable control.cece, why can not affect ce counter and status.ceco bit?

The overwrite rules do not change counting of corrected errors. If `cece` is 1, then CE will count in `cec` and if an overflow occurs will set the `ceco` bit.

> I have a question: when ue has logged in status register, if ce occurs, it will set status.ce bit and trigger ce interrupt, but if enable control.cece, why can not affect ce counter and status.ceco bit?

The `ceco` indicates status of the counter overflow. The corrected error counting and overflow signaling is not affected by the overwrite rules i.e. CE are counted even if they are not recorded.
